{{- if and (not .Values.externalSecret.enabled) (or .Values.externalPostgres.enabled .Values.postgresql.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dify.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
data:
  {{- include "dify.db.credentials" . | nindent 2 }}
{{- end }}