{{- if and (not .Values.externalSecret.enabled) (or .Values.externalRedis.enabled .Values.redis.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dify.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- include "dify.redis.credentials" . | nindent 2 }}
{{- end }}