{{- if and .Values.redis.enabled .Values.externalSecret.enabled .Values.externalSecret.redis.connection.enabled }}
{{- $redisConnectionSecretName := printf "%s-redis-connection" (include "dify.fullname" .) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $redisConnectionSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-connection
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ $redisConnectionSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{- with .Values.externalSecret.redis.connection.data }}
        {{- range $key, $value := . }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
  data:
    {{- if .Values.externalSecret.redis.connection.remoteRefs }}
    {{- range $secretKey, $remoteRef := .Values.externalSecret.redis.connection.remoteRefs }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $remoteRef.key }}
        {{- if $remoteRef.property }}
        property: {{ $remoteRef.property }}
        {{- end }}
        {{- if $remoteRef.decodingStrategy }}
        decodingStrategy: {{ $remoteRef.decodingStrategy }}
        {{- else if $.Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ $.Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- end }}
{{- end }}