{{- if and .Values.redis.enabled .Values.externalSecret.enabled .Values.externalSecret.redis.auth.enabled .Values.redis.auth.enabled (not .Values.redis.auth.password) }}
{{- $redisAuthSecretName := .Values.redis.auth.existingSecret | default (printf "%s-redis-auth" (include "dify.fullname" .)) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $redisAuthSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis-auth
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ $redisAuthSecretName }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{- if index .Values.externalSecret.redis.auth.remoteRefs "redis-password" }}
        redis-password: "{{ `{{ index . \"redis-password\" }}` }}"
        {{- end }}
  data:
    {{- if .Values.externalSecret.redis.auth.remoteRefs }}
    {{- range $secretKey, $remoteRef := .Values.externalSecret.redis.auth.remoteRefs }}
    - secretKey: {{ $secretKey }}
      remoteRef:
        key: {{ $remoteRef.key }}
        {{- if $remoteRef.property }}
        property: {{ $remoteRef.property }}
        {{- end }}
        {{- if $remoteRef.decodingStrategy }}
        decodingStrategy: {{ $remoteRef.decodingStrategy }}
        {{- else if $.Values.externalSecret.decodingStrategy }}
        decodingStrategy: {{ $.Values.externalSecret.decodingStrategy }}
        {{- end }}
        conversionStrategy: Default
        metadataPolicy: None
    {{- end }}
    {{- end }}
{{- end }}