{{- if and (not .Values.externalSecret.enabled) .Values.externalS3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dify.fullname" . }}-s3
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dify.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
type: Opaque
data:
  {{- include "dify.s3.credentials" . | nindent 2 }}
{{- end }}